// Schematic only: direction hints, never continuous physical localization.
// Every simulated checkpoint assumes the user faces the TOP of the floor plan.
export const layout = {
  terrace_entry: { x: 4, y: 16 },
  terrace_door: { x: 4, y: 14 },
  left_hall_lower: { x: 4, y: 13 },
  right_hall_lower: { x: 10, y: 13 },
  living_left_entry: { x: 5, y: 13 },
  living_room: { x: 7, y: 13 },
  living_right_entry: { x: 9, y: 13 },
  left_hall_room_1: { x: 4, y: 10 },
  room_1_entry: { x: 3, y: 10 },
  left_hall_middle: { x: 4, y: 8.5 },
  room_2_entry: { x: 3, y: 8.5 },
  left_hall_upper: { x: 4, y: 4.5 },
  upper_hall: { x: 7, y: 4.5 },
  right_hall_upper: { x: 10, y: 4.5 },
  right_hall_middle: { x: 10, y: 8.5 },
  room_3_entry: { x: 11, y: 8.5 },
  right_hall_room_4: { x: 10, y: 10 },
  room_4_entry: { x: 11, y: 10 },
  dining_room: { x: 7, y: 2 },
  kitchen_approach: { x: 10, y: 1 },
  kitchen_entry: { x: 11, y: 1 },
  bathroom_2_approach: { x: 4, y: 2 },
  bathroom_2_entry: { x: 3, y: 2 },
  bathroom_1_door: { x: 3, y: 5 },
  bathroom_1_entry: { x: 3, y: 4.5 },
};
